config/routes.rb
SocietyMgmt::Application.routes.draw do
  resources :comments

  resources :vendors

  resources :proposals

  resources :flats

  resources :resolutions

  resources :minutes

  resources :meetings

  resources :uploads

  resources :messages

  resources :designations

  devise_for :users

  root :to=>'welcome#index'
  match "sent_messages"=>'messages#sent_messages'

end

app/models/designation.rb
class Designation < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me  ,:username,:first_name,:last_name,:designation_id,:dashboard_id

  #the relationships
  has_many :uploads
  has_many :messages
  has_many :flats
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def javascript(*files)
     content_for(:head) { javascript_include_tag(*files) }
   end

end

app/controllers/designations_controller.rb
class DesignationsController < ApplicationController
  # GET /designations
  # GET /designations.json
  def index
    @designations = Designation.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @designations }
    end
  end

  # GET /designations/1
  # GET /designations/1.json
  def show
    @designation = Designation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @designation }
    end
  end

  # GET /designations/new
  # GET /designations/new.json
  def new
    @designation = Designation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @designation }
    end
  end

  # GET /designations/1/edit
  def edit
    @designation = Designation.find(params[:id])
  end

  # POST /designations
  # POST /designations.json
  def create
    @designation = Designation.new(params[:designation])

    respond_to do |format|
      if @designation.save
        format.html { redirect_to @designation, notice: 'Designation was successfully created.' }
        format.json { render json: @designation, status: :created, location: @designation }
      else
        format.html { render action: "new" }
        format.json { render json: @designation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /designations/1
  # PUT /designations/1.json
  def update
    @designation = Designation.find(params[:id])

    respond_to do |format|
      if @designation.update_attributes(params[:designation])
        format.html { redirect_to @designation, notice: 'Designation was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @designation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /designations/1
  # DELETE /designations/1.json
  def destroy
    @designation = Designation.find(params[:id])
    @designation.destroy

    respond_to do |format|
      format.html { redirect_to designations_url }
      format.json { head :ok }
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    #this is the action for home page(first page)
    #retrieving the flat information for current user
    @flats=current_user.flats if current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/designations_helper.rb
module DesignationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/designations/_form.html.erb
<%= form_for(@designation) do |f| %>
  <% if @designation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@designation.errors.count, "error") %> prohibited this designation from being saved:</h2>

      <ul>
      <% @designation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/designations/edit.html.erb
<h1>Editing designation</h1>

<%= render 'form' %>

<%= link_to 'Show', @designation %> |
<%= link_to 'Back', designations_path %>

app/views/designations/index.html.erb
<h1>Listing designations</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @designations.each do |designation| %>
  <tr>
    <td><%= designation.name %></td>
    <td><%= link_to 'Show', designation %></td>
    <td><%= link_to 'Edit', edit_designation_path(designation) %></td>
    <td><%= link_to 'Destroy', designation, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Designation', new_designation_path %>

app/views/designations/new.html.erb
<h1>New designation</h1>

<%= render 'form' %>

<%= link_to 'Back', designations_path %>

app/views/designations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @designation.name %>
</p>


<%= link_to 'Edit', edit_designation_path(@designation) %> |
<%= link_to 'Back', designations_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SocietyMgmt</title>

  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "application" %>
  <%= yield(:head) %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/messages/_index.html.erb
<h1>Listing messages</h1>

<table>
  <tr>
    <th>From</th>
    <th>To</th>
    <th>Subject</th>
    <th>Body</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @messages.each do |message| %>
      <tr>
        <td><%= message.from_id %></td>

        <td><%= message.subject %></td>
        <td><%= message.body %></td>
        <td><%= link_to 'Show', message %></td>
        <td><%= link_to 'Edit', edit_message_path(message) %></td>
        <td><%= link_to 'Destroy', message, confirm: 'Are you sure?', method: :delete %></td>
      </tr>
  <% end %>
</table>

<br/>

<%= link_to 'New Message', new_message_path %>

app/views/messages/sent_messages.html.erb
<%= render "index"  %>

app/views/welcome/index.html.erb
<h2>Welcome to Society Management Portal</h2>


<% if current_user %>
    <p>Welcome <%= current_user.username %></p>

    <%= link_to "Sign Out", destroy_user_session_path, :method => :delete %> |
    <%= link_to "Edit Profile", edit_user_registration_path %>|
    <%= link_to "new upload", new_upload_path %>|
    <%= link_to "Fix a new Meeting upload", new_meeting_path %> |
    <% if @flats.blank? %>
        <%= link_to "Add Flat Information", new_flat_path %>
    <% else %>
        <%= link_to "View Flat Information", flats_path %>
    <% end %>
    <hr>

    <div id="dashboard">
      <p>
        This is user specific data for dashboard<br>
        This section act as a dashboard...<br>
        This will contain sections for scheduled meetings,messages and new resolution<br>

      <p id="notice"><%= notice %></p>
      <br>
      <br>
      <br>

      <%= link_to "View All Meetings", meetings_path %> |
      <%= link_to "View Inbox", messages_path %>  |
      <%= link_to "View Sent Messages", sent_messages_path %>  |
      <%= link_to "View All Resolutions", resolutions_path %> |
      <%= link_to "View All Proposals",proposals_path %>




    </div>


<% else %>

    <%= link_to "Sign In", new_user_session_path %>
<% end %>